export { default as WelcomeWindow } from "./WelcomeWindow";
export { default as AboutWindow } from "./AboutWindow";
export { default as SkillsWindow } from "./SkillsWindow";
export { default as ProjectsWindow } from "./ProjectsWindow";
export { default as CalculatorWindow } from "./CalculatorWindow";
export { default as UtilWindow } from "./UtilWindow";
export { default as ResumeWindow } from "./ResumeWindow";
export { default as TerminalWindow } from "./TerminalWindow";
export { default as SettingsWindow } from "./SettingsWindow";
