/** Official site for each skill — clicking a skill opens it in a new tab. */
const SKILL_LINKS: Record<string, string> = {
  React: "https://react.dev",
  Vue: "https://vuejs.org",
  Angular: "https://angular.dev",
  Nextjs: "https://nextjs.org",
  Redux: "https://redux.js.org",
  jQuery: "https://jquery.com",
  Bootstrap: "https://getbootstrap.com",
  SASS: "https://sass-lang.com",
  Tailwind: "https://tailwindcss.com",
  "styled-components": "https://styled-components.com",
  "Node.js": "https://nodejs.org",
  Express: "https://expressjs.com",
  NestJS: "https://nestjs.com",
  AWS: "https://aws.amazon.com",
  Spring: "https://spring.io",
  Laravel: "https://laravel.com",
  MongoDB: "https://www.mongodb.com",
  "ASP.Net Core": "https://learn.microsoft.com/aspnet/core",
  "React Native": "https://reactnative.dev",
  Flutter: "https://flutter.dev",
  Swift: "https://www.swift.org",
  TypeScript: "https://www.typescriptlang.org",
  JavaScript: "https://developer.mozilla.org/docs/Web/JavaScript",
  Python: "https://www.python.org",
  Java: "https://dev.java",
  "C#": "https://learn.microsoft.com/dotnet/csharp/",
  Dart: "https://dart.dev",
  "C/C++": "https://isocpp.org",
  PHP: "https://www.php.net",
  HTML5: "https://developer.mozilla.org/docs/Web/HTML",
  CSS3: "https://developer.mozilla.org/docs/Web/CSS",
  MySQL: "https://www.mysql.com",
  "PL/SQL": "https://www.oracle.com/database/technologies/appdev/plsql.html",
  R: "https://www.r-project.org",
};

export const getSkillLink = (name: string): string | undefined => SKILL_LINKS[name];

export default SKILL_LINKS;
